// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package server

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Добавление вакансии
	// (POST /api/vacancies/addVacancy)
	PostApiVacanciesAddVacancy(w http.ResponseWriter, r *http.Request)
	// Удаляется вакансия
	// (DELETE /api/vacancies/delete/{vacancy-id})
	DeleteApiVacanciesDeleteVacancyId(w http.ResponseWriter, r *http.Request, vacancyId int)
	// Получение всех вакансий
	// (GET /api/vacancies/getAllVacancy)
	GetApiVacanciesGetAllVacancy(w http.ResponseWriter, r *http.Request)
	// Получение вакансии по VacancyID
	// (GET /api/vacancies/getVacancyByEmployerID/{employer_id})
	GetApiVacanciesGetVacancyByEmployerIDEmployerId(w http.ResponseWriter, r *http.Request, employerId int)
	// Получение вакансии по VacancyID
	// (GET /api/vacancies/getVacancyByVacancyID/{id})
	GetApiVacanciesGetVacancyByVacancyIDId(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Добавление вакансии
// (POST /api/vacancies/addVacancy)
func (_ Unimplemented) PostApiVacanciesAddVacancy(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удаляется вакансия
// (DELETE /api/vacancies/delete/{vacancy-id})
func (_ Unimplemented) DeleteApiVacanciesDeleteVacancyId(w http.ResponseWriter, r *http.Request, vacancyId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение всех вакансий
// (GET /api/vacancies/getAllVacancy)
func (_ Unimplemented) GetApiVacanciesGetAllVacancy(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение вакансии по VacancyID
// (GET /api/vacancies/getVacancyByEmployerID/{employer_id})
func (_ Unimplemented) GetApiVacanciesGetVacancyByEmployerIDEmployerId(w http.ResponseWriter, r *http.Request, employerId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получение вакансии по VacancyID
// (GET /api/vacancies/getVacancyByVacancyID/{id})
func (_ Unimplemented) GetApiVacanciesGetVacancyByVacancyIDId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiVacanciesAddVacancy operation middleware
func (siw *ServerInterfaceWrapper) PostApiVacanciesAddVacancy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiVacanciesAddVacancy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiVacanciesDeleteVacancyId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiVacanciesDeleteVacancyId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vacancy-id" -------------
	var vacancyId int

	err = runtime.BindStyledParameterWithOptions("simple", "vacancy-id", chi.URLParam(r, "vacancy-id"), &vacancyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vacancy-id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiVacanciesDeleteVacancyId(w, r, vacancyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiVacanciesGetAllVacancy operation middleware
func (siw *ServerInterfaceWrapper) GetApiVacanciesGetAllVacancy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiVacanciesGetAllVacancy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiVacanciesGetVacancyByEmployerIDEmployerId operation middleware
func (siw *ServerInterfaceWrapper) GetApiVacanciesGetVacancyByEmployerIDEmployerId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "employer_id" -------------
	var employerId int

	err = runtime.BindStyledParameterWithOptions("simple", "employer_id", chi.URLParam(r, "employer_id"), &employerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "employer_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiVacanciesGetVacancyByEmployerIDEmployerId(w, r, employerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiVacanciesGetVacancyByVacancyIDId operation middleware
func (siw *ServerInterfaceWrapper) GetApiVacanciesGetVacancyByVacancyIDId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiVacanciesGetVacancyByVacancyIDId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/vacancies/addVacancy", wrapper.PostApiVacanciesAddVacancy)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/vacancies/delete/{vacancy-id}", wrapper.DeleteApiVacanciesDeleteVacancyId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/vacancies/getAllVacancy", wrapper.GetApiVacanciesGetAllVacancy)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/vacancies/getVacancyByEmployerID/{employer_id}", wrapper.GetApiVacanciesGetVacancyByEmployerIDEmployerId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/vacancies/getVacancyByVacancyID/{id}", wrapper.GetApiVacanciesGetVacancyByVacancyIDId)
	})

	return r
}
