// Package server Code generated by swaggo/swag. DO NOT EDIT
package server

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ratings/addRating": {
            "post": {
                "description": "При обращении, добавляется отклик в БД по телу запрсоа",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIs"
                ],
                "summary": "Добавление отклика в БД",
                "parameters": [
                    {
                        "description": "Тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rating"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос выполнен успешно"
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/api/ratings/{username}": {
            "get": {
                "description": "При обращении, возвращаются все ответы, которые есть у username",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIs"
                ],
                "summary": "Получение ответов по username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID пользователя",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос выполнен успешно",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/rating"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "rating": {
            "type": "object",
            "properties": {
                "from_user": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "rating_id": {
                    "type": "integer"
                },
                "to_user": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "localhost:8008",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Authentication API",
 Description:"# Postgres\n"+
"",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
