// Package server Code generated by swaggo/swag. DO NOT EDIT
package server

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/checkSeeker/{username}": {
            "get": {
                "description": "При обращении, регистрируется соискатель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIs"
                ],
                "summary": "Проверка, существует ли пользователь",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username пользователя",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос выполнен успешно",
                        "schema": {
                            "$ref": "#/definitions/seeker"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/api/login": {
            "get": {
                "description": "Генерирует JWT токен",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Получение токена",
                "responses": {
                    "200": {
                        "description": "Запрос выполнен успешно",
                        "schema": {
                            "$ref": "#/definitions/token_response"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/api/registerSeeker": {
            "post": {
                "description": "При обращении, регистрируется соискатель",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIs"
                ],
                "summary": "Регистрация соискателя",
                "parameters": [
                    {
                        "description": "Данные о пользователе",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/seeker"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Запрос выполнен успешно"
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/api/update/{username}": {
            "put": {
                "description": "При обращении, обновляются данные",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APIs"
                ],
                "summary": "Обновление данных о пользователе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username пользователя",
                        "name": "username",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/seeker"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос выполнен успешно"
                    },
                    "400": {
                        "description": "Ошибка валидации данных"
                    },
                    "401": {
                        "description": "Ошибка авторизации"
                    },
                    "500": {
                        "description": "Произошла внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "seeker": {
            "type": "object",
            "properties": {
                "f_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password_hash": {
                    "type": "string"
                },
                "resume": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "token_response": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1N74VlQTsu4TStQiloLfN0ENf6d64Ar0uSbrvtbUqFMGQ"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 18000
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "localhost:8005",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Authentication API",
 Description:"# Postgres\n"+
"",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
